// Auto-generated by scripts/generate-schema-types.ts

export interface GlobalsSchema {
    phone?: string;
    email?: string;
    address?: string;
    city?: string;
    country?: string;
    facebookUrl?: string;
    twitterUrl?: string;
    instagramUrl?: string;
    linkedinUrl?: string;
    youtubeUrl?: string;
    siteName?: string;
    siteEmail?: string;
    siteDescription?: string;
}
