// Auto-generated by scripts/generate-schema-types.ts

export interface HeroSchemaData {
    launchDate?: string;
    eventDate?: string;
    workdayDate?: string;
    customDate?: string;
    birthDate?: string;
    typedDate?: string;
    eventDateRange?: string;
    ctaButton?: string;
    ctaLinkType?: string;
    ctaInternalLink?: string;
    title?: string;
    subtitle?: string;
    subtitle_test?: string;
    cards?: any[];
}
