// Auto-generated by scripts/generate-schema-types.ts

export interface CardData {
    title?: string;
    description?: string;
}

export interface HeroSchemaData {
    launchDate?: Date;
    eventDate?: Date;
    workdayDate?: Date;
    customDate?: Date;
    birthDate?: Date;
    typedDate?: Date;
    eventDateRange?: Date;
    ctaButton?: string;
    ctaLinkType?: string;
    ctaInternalLink?: string;
    title?: string;
    subtitle?: string;
    subtitle_test?: string;
    cards?: CardData[];
}
