// Auto-generated by scripts/generate-schema-types.ts

export interface CardData {
    title: string;
    description?: string;
}

export interface HeroSchemaData {
    launchDate?: Date;
    eventDate: Date;
    workdayDate?: Date;
    customDate?: Date;
    birthDate?: Date;
    typedDate: Date;
    eventDateRange: Date;
    ctaButton: string;
    ctaLinkType: string;
    ctaInternalLink: string;
    ctaExternalLink?: string;
    title: string;
    subtitle: string;
    test_rich: string;
    subtitle_test: string;
    cards?: CardData[];
}
