// Auto-generated by scripts/generate-schema-types.ts

export interface FooterSchemaData {
    companyName: string;
    description?: string;
    email: string;
    phone?: string;
    address?: string;
}
