name = "capsulo-file-upload"
main = "src/index.ts"
compatibility_date = "2024-10-29"

[env.production]
vars = { ALLOWED_ORIGINS = "https://your-domain.com" }

[env.development]
vars = { ALLOWED_ORIGINS = "http://localhost:4321,http://localhost:4322" }
