name = "capsulo-file-upload"
main = "src/index.ts"
compatibility_date = "2024-10-29"

[vars]
ALLOWED_ORIGINS = "http://localhost:4321,http://localhost:4322"
CLOUDFLARE_R2_PUBLIC_URL = "https://pub-778f9cca88fe4e77a7390d4fccc06ec1.r2.dev"

[env.production.vars]
ALLOWED_ORIGINS = "https://your-domain.com"
CLOUDFLARE_R2_PUBLIC_URL = "https://pub-778f9cca88fe4e77a7390d4fccc06ec1.r2.dev"

[env.development.vars]
ALLOWED_ORIGINS = "http://localhost:4321,http://localhost:4322"
CLOUDFLARE_R2_PUBLIC_URL = "https://pub-778f9cca88fe4e77a7390d4fccc06ec1.r2.dev"
